apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-service
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-service
  template:
    metadata:
      labels:
        app: vote-service
    spec:
      containers:
        - name: vote-service
          image: mishel1113/vote-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: db-secret
          env:
            - name: Services__SalaryService
              value: http://salary-service

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10

          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
