apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: app
type: Opaque
stringData:
  ConnectionStrings__Postgres: Host=postgres.data.svc.cluster.local;Port=5432;Database=salarydb;Username=postgres;Password=Admin@123
  Jwt__Secret: dev-secret-key-minimum-32-characters-long!!
