apiVersion: v1
kind: Secret
metadata:
  name: identity-service-secret
  namespace: app
type: Opaque
stringData:
  jwt-secret: "CHANGE_ME_TO_A_STRONG_SECRET_AT_LEAST_32_CHARS"
  db-password: "changeme"
